config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires
  root to: 'questionnaires#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true

  enum question_type: { single_choice: 0, multiple_choice: 1, long_answer: 2 }

  def self.question_type_select
    question_types.keys.map { |k| [k.titleize, k] }
  end
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[ show edit update destroy ]

  def index
    @questionnaires = Questionnaire.all
  end

  def show
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def edit
  end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    if @questionnaire.save
      redirect_to @questionnaire, notice: 'Questionnaire was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @questionnaire.update(questionnaire_params)
      redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @questionnaire.destroy
    redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.'
  end

  private

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:id])
  end

  def questionnaire_params
    params.require(:questionnaire).permit(
      :name,
      questions_attributes: [
        :_destroy,
        :id,
        :question_type,
        :name,
        answers_attributes: [:_destroy, :id, :name]
      ]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stimulus_include_tags %>
    <%= javascript_include_tag "turbo", type: "module-shim" %>
    <%= yield :head %>
  </head>

  <body>
    <div class="container">
      <%= link_to "Home", root_path %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questionnaires/_answer_fields.html.erb
<div class='nested-fields'>
  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Answer', class: 'form-control' %>
    <small>
      <%= link_to "Remove Answer", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>
</div>

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div data-controller="nested-form">
    <template data-nested-form-target='template'>
      <%= form.fields_for :questions, Question.new, child_index: 'TEMPLATE_RECORD' do |question| %>
        <%= render 'question_fields', form: question %>
      <% end %>
    </template>

    <%= form.fields_for :questions do |question| %>
      <%= render 'question_fields', form: question %>
    <% end %>

    <div data-nested-form-target="add_item">
      <%= link_to "Add Question", "#", data: { action: "nested-form#add_association" } %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questionnaires/_question_fields.html.erb
<div class='nested-fields box' data-controller='dynamic-select'>
  <div class='form-group'>
    <%= form.select :question_type,
        options_for_select(Question.question_type_select, selected: form.object.question_type),
        {},
        'data-dynamic-select-target': 'select',
        'data-action': 'dynamic-select#selected' %>
  </div>

  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Question', class: 'form-control' %>
    <small>
      <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>

  <div data-controller="nested-form" data-dynamic-select-target='choice'>
    <template data-nested-form-target='template'>
      <%= form.fields_for :answers, Answer.new, child_index: 'TEMPLATE_RECORD' do |answer| %>
        <%= render 'answer_fields', form: answer %>
      <% end %>
    </template>

    <%= form.fields_for :answers do |answer| %>
      <%= render 'answer_fields', form: answer %>
    <% end %>

    <div data-nested-form-target="add_item">
      <%= link_to "Add Answer", "#", data: { action: "nested-form#add_association" } %>
    </div>
  </div>

  <div data-controller="nested-form" data-dynamic-select-target='long'>
  </div>
</div>

app/views/questionnaires/edit.html.erb
<h1>Editing Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questionnaires</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= questionnaire.name %></td>
        <td><%= link_to 'Show', questionnaire %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
        <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

app/views/questionnaires/new.html.erb
<h1>New Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @questionnaire.name %></h1>

<% @questionnaire.questions.each do |question| %>
  <h2><%= question.name %></h2>

  <% case question.question_type %>
  <% when 'single_choice' %>
    <% question.answers.each do |answer| %>
      <p>
        <%= radio_button_tag question.id, answer.id %>
        <%= answer.name %>
      </p>
    <% end %>
  <% when 'multiple_choice' %>
    <% question.answers.each do |answer| %>
      <p>
        <%= check_box_tag question.id, answer.id %>
        <%= answer.name %>
      </p>
    <% end %>
  <% when 'long_answer' %>
    <%= text_area_tag question.id %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>